//  reviews{
//     data{
//       id
//       attributes{
//         text
//         type
//         isDispute
//          isClosed
//         likes
//         isApproved
//         categories
//         userAgent
//         location
//   updatedAt
// screenshots{
//   data{
//     attributes{
//       name
//       alternativeText
//       url
//     }
//   }
// }
//         review_replies{
//           data{
//             id
//             attributes{
//               text
//               from
//               likes
//               iaApproved
//               updatedAt
//               screenshots{
//                 data{
//                   attributes{
//                     name
//                     alternativeText
//                     url
//                   }
//                 }
//               }
//             }
//           }
//         }
//       }
//     }
//   }

// top_parameter{
// data{
//   attributes{
//     code
// parameter{
//   en_description
//   ru_description
// icon{
//   data{
//     id
//     attributes{
//       alternativeText
//       name
//       url
//     }
//   }
// }
// }
//   }
// }}
